### ISSUE TITLE
Theory

### ISSUE THREAD

**Issue by tiagovla** [LaurentNevou/Light_PhotonicCrystal_2D#1]
Not an issue, but a question.

Is there a paper or book where I can find the theory of how this works/was coded, ideally for 2D and 3D?

The version I've seen before uses convolution matrices.

**Comment by LaurentNevou** [comment]
Sorry for my late answer but I don t receive any warning when someone is writing me...
here it is:
Igor A. Sukhoivanov and Igor V. Guryev
Photonic Cristals: Physical and Practical Modeling
